"""Metadata library for manual image assets and placeholders."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from content_system.live_methodology_agent_utils import SCHEMA_VERSION, make_id
from content_system.paths import ProjectPaths
from content_system.phase7_report_utils import list_payload, read_json, repo_relative, today_token, utc_now, write_json_and_markdown


def output_paths(paths: ProjectPaths) -> dict[str, Path]:
    root = paths.market_content_root / "08_assets"
    return {
        "memory_json": root / "image_asset_library.json",
        "memory_md": root / "image_asset_library.md",
        "board_md": paths.frontstage_root / "image_asset_library_board.md",
    }


def ensure_asset_dirs(paths: ProjectPaths) -> None:
    (paths.market_content_root / "08_assets" / "images").mkdir(parents=True, exist_ok=True)


def summary_for(assets: list[dict[str, Any]]) -> dict[str, int]:
    return {
        "asset_count": len(assets),
        "available": sum(1 for item in assets if item.get("asset_status") == "AVAILABLE"),
        "placeholder": sum(1 for item in assets if item.get("asset_status") == "PLACEHOLDER"),
        "needs_review": sum(1 for item in assets if item.get("asset_status") == "NEEDS_REVIEW"),
        "wechat_ready": sum(1 for item in assets if item.get("wechat_ready")),
    }


def build_placeholder_asset(paths: ProjectPaths, task: dict[str, Any]) -> dict[str, Any]:
    run_date = today_token()
    asset_id = make_id("imgasset", run_date, task.get("task_id"), task.get("source_request_id"))
    return {
        "asset_id": asset_id,
        "task_id": task.get("task_id") or "",
        "article_id": task.get("article_id") or "",
        "visual_id": "",
        "visual_type": task.get("visual_type") or "",
        "asset_status": "PLACEHOLDER",
        "asset_path": task.get("expected_asset_path") or "",
        "source_type": "placeholder",
        "source_note": "Placeholder metadata from manual image generation task; no image file generated by system.",
        "copyright_note": "Human must confirm rights before use.",
        "usage_note": task.get("design_brief") or "",
        "wechat_ready": False,
        "human_review_required": True,
        "created_at": utc_now(),
    }


def update_image_asset_library(paths: ProjectPaths, repo_root: Path) -> tuple[dict[str, Any], dict[str, Path]]:
    ensure_asset_dirs(paths)
    root = paths.market_content_root / "08_assets"
    existing = read_json(root / "image_asset_library.json")
    tasks_payload = read_json(root / "latest_manual_image_generation_tasks.json")
    assets_by_task = {str(item.get("task_id")): item for item in list_payload(existing, "assets") if item.get("task_id")}
    assets_by_id = {str(item.get("asset_id")): item for item in list_payload(existing, "assets") if item.get("asset_id")}
    for task in list_payload(tasks_payload, "tasks"):
        task_id = str(task.get("task_id") or "")
        if task_id and task_id not in assets_by_task:
            asset = build_placeholder_asset(paths, task)
            assets_by_task[task_id] = asset
            assets_by_id[str(asset.get("asset_id"))] = asset
    assets = sorted(assets_by_id.values(), key=lambda item: str(item.get("created_at") or item.get("asset_id") or ""))
    payload = {
        "schema_version": SCHEMA_VERSION,
        "updated_at": utc_now(),
        "assets": assets,
        "summary": summary_for(assets),
        "policy": {"metadata_only": True, "image_files_not_committed": True, "human_review_required": True},
    }
    outputs = output_paths(paths)
    write_json_and_markdown(payload, render_markdown(payload), outputs)
    payload["outputs"] = {key: repo_relative(path, repo_root) for key, path in outputs.items()}
    return payload, outputs


def update_asset(paths: ProjectPaths, repo_root: Path, asset_id: str, *, status: str, asset_path: str = "", note: str = "") -> tuple[dict[str, Any], dict[str, Path]]:
    payload, _ = update_image_asset_library(paths, repo_root)
    for asset in list_payload(payload, "assets"):
        if asset.get("asset_id") != asset_id:
            continue
        asset["asset_status"] = status
        if asset_path:
            asset["asset_path"] = asset_path
        if note:
            asset["source_note"] = note
        if status == "AVAILABLE":
            asset["source_type"] = asset.get("source_type") if asset.get("source_type") != "placeholder" else "manual_design"
            asset["wechat_ready"] = False
            asset["human_review_required"] = True
        if status == "REJECTED":
            asset["wechat_ready"] = False
    payload["summary"] = summary_for(list_payload(payload, "assets"))
    outputs = output_paths(paths)
    write_json_and_markdown(payload, render_markdown(payload), outputs)
    payload["outputs"] = {key: repo_relative(path, repo_root) for key, path in outputs.items()}
    return payload, outputs


def render_markdown(payload: dict[str, Any]) -> str:
    summary = payload.get("summary") if isinstance(payload.get("summary"), dict) else {}
    rows = "\n".join(
        f"| `{item.get('asset_id')}` | `{item.get('task_id')}` | `{item.get('visual_type')}` | `{item.get('asset_status')}` | `{item.get('wechat_ready')}` | `{item.get('asset_path')}` |"
        for item in list_payload(payload, "assets")
    ) or "| - | - | - | - | false | No image assets registered |"
    return f"""# Image Asset Library

## Summary

- asset_count: `{summary.get('asset_count', 0)}`
- available: `{summary.get('available', 0)}`
- placeholder: `{summary.get('placeholder', 0)}`
- needs_review: `{summary.get('needs_review', 0)}`
- wechat_ready: `{summary.get('wechat_ready', 0)}`

| Asset | Task | Visual Type | Status | WeChat Ready | Path |
|---|---|---|---|---|---|
{rows}
"""
